# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=300, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='recentlyinwork',
            name='img',
            field=models.ImageField(upload_to='media/', verbose_name='Изображение'),
        ),
    ]
