# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170129_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=300, verbose_name='Телефон'),
        ),
    ]
